# Generated by Django 3.1.5 on 2021-01-28 07:55

import ckeditor.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='serial Number')),
                ('img_1', models.ImageField(upload_to='realestate/aboutus', verbose_name='About Header Image')),
                ('img_2', models.ImageField(upload_to='realestate/aboutus', verbose_name='Image')),
                ('paragraph', models.CharField(max_length=100, verbose_name='Main Paragrph')),
                ('point_1', models.CharField(max_length=50, verbose_name='Point one')),
                ('point_2', models.CharField(max_length=50, verbose_name='Point two')),
                ('point_3', models.CharField(max_length=50, verbose_name='Point three')),
                ('content', ckeditor.fields.RichTextField(verbose_name='About Us Content Box')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Artitecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Architecture Name')),
                ('img', models.ImageField(upload_to='realestate/architecture', verbose_name='Image')),
                ('about_me', ckeditor.fields.RichTextField(verbose_name='About Me')),
                ('social_link_1', models.URLField(blank=True, verbose_name='Twitter link')),
                ('social_link_2', models.URLField(blank=True, verbose_name='Facebook Link')),
                ('social_link_3', models.URLField(blank=True, verbose_name='Instagram link')),
                ('social_link_4', models.URLField(blank=True, verbose_name='Linkedin link')),
                ('number', models.PositiveIntegerField(verbose_name='Serical Number')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Messsage')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Serial Number')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Why Contact Us')),
                ('location', models.CharField(max_length=2000, verbose_name='google location')),
                ('address', models.CharField(max_length=20, verbose_name='Address')),
                ('country', models.CharField(default='India', max_length=10, verbose_name='Country')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('tollfree', models.CharField(max_length=13, verbose_name='Toll Free Number')),
                ('social_link_1', models.URLField(blank=True, verbose_name='Twitter link')),
                ('social_link_2', models.URLField(blank=True, verbose_name='Facebook Link')),
                ('social_link_3', models.URLField(blank=True, verbose_name='Instagram link')),
                ('social_link_4', models.URLField(blank=True, verbose_name='Linkedin link')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Question Number')),
                ('question', models.CharField(max_length=50, verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Answer of this question')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Featur Serial Number')),
                ('icon', models.CharField(max_length=23, verbose_name='Icon')),
                ('title', models.CharField(max_length=100, verbose_name='Feature Name')),
                ('img', models.ImageField(upload_to='realestate/feature', verbose_name='Image of Work')),
                ('paragraph', ckeditor.fields.RichTextField(verbose_name='Feature Discription')),
                ('point_1', models.CharField(blank=True, max_length=50, verbose_name='Point one')),
                ('point_2', models.CharField(blank=True, max_length=50, verbose_name='Point two')),
                ('point_3', models.CharField(blank=True, max_length=50, verbose_name='Point three')),
                ('point_4', models.CharField(blank=True, max_length=50, verbose_name='Point Four')),
                ('point_5', models.CharField(blank=True, max_length=50, verbose_name='Point Five')),
                ('point_6', models.CharField(blank=True, max_length=50, verbose_name='Point Six')),
                ('point_7', models.CharField(blank=True, max_length=50, verbose_name='Point Seven')),
                ('point_8', models.CharField(blank=True, max_length=50, verbose_name='Point Eight')),
                ('point_9', models.CharField(blank=True, max_length=50, verbose_name='Point Nine')),
                ('point_10', models.CharField(blank=True, max_length=50, verbose_name='Point Ten')),
                ('point_11', models.CharField(blank=True, max_length=50, verbose_name='Point Eleven')),
                ('point_12', models.CharField(blank=True, max_length=50, verbose_name='Point Twele')),
                ('point_13', models.CharField(blank=True, max_length=50, verbose_name='Point Thirteen')),
                ('point_14', models.CharField(blank=True, max_length=50, verbose_name='Point Fourteen')),
                ('point_15', models.CharField(blank=True, max_length=50, verbose_name='Point Fifteen')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Company Name')),
                ('paragraph', models.CharField(max_length=50, verbose_name='Content Box')),
                ('link_1', models.URLField(verbose_name='Twitter link')),
                ('link_2', models.URLField(verbose_name='Facebook link')),
                ('link_3', models.URLField(verbose_name='Instagram link')),
                ('link_4', models.URLField(verbose_name='Linkedin link')),
                ('serial_number', models.PositiveIntegerField(verbose_name='Serial Number')),
            ],
            options={
                'ordering': ['-serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=16, verbose_name='Poperty Id')),
                ('property_type', models.CharField(max_length=20, verbose_name='Type Of Property')),
                ('status', models.CharField(choices=[('For Sell', 'For Sell'), ('For Rent', 'For Rent')], max_length=10, verbose_name='Perpose')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('header_img', models.ImageField(upload_to='realestate/header', verbose_name='Header Image')),
                ('additional_img_1', models.ImageField(upload_to='realestate/property', verbose_name='Side image')),
                ('additional_img_2', models.ImageField(upload_to='realestate/property', verbose_name='Side image')),
                ('property_video', models.CharField(max_length=2000, verbose_name='Iframe of your property video')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('content', models.CharField(max_length=200, verbose_name='Content Box')),
                ('about_this', ckeditor.fields.RichTextField(verbose_name='About This Project')),
                ('loacation', models.CharField(max_length=2000, verbose_name='Google location of Property')),
                ('number', models.PositiveIntegerField(verbose_name='Serial Number')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('area', models.PositiveIntegerField(verbose_name='Area In Squre Ft.')),
                ('hall', models.PositiveIntegerField(verbose_name='Number of Hall')),
                ('beds', models.PositiveIntegerField(verbose_name='Number of Bedroom')),
                ('bath', models.PositiveIntegerField(verbose_name='Nomber of Baths')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name=' Serial Number')),
                ('price', models.PositiveIntegerField(verbose_name='service charge')),
                ('parameter', models.CharField(max_length=10, verbose_name='basis of parameter like (month,squre ft,squre meeter etc.)')),
                ('title', models.CharField(max_length=50, verbose_name='Package Name')),
                ('service_1', models.CharField(blank=True, max_length=100, verbose_name='Service')),
                ('service_2', models.CharField(blank=True, max_length=100, verbose_name='Service number two')),
                ('service_3', models.CharField(blank=True, max_length=100, verbose_name='Service number three')),
                ('service_4', models.CharField(blank=True, max_length=100, verbose_name='Service number four')),
                ('service_5', models.CharField(blank=True, max_length=100, verbose_name='Service number five')),
                ('service_6', models.CharField(blank=True, max_length=100, verbose_name='Service')),
                ('service_7', models.CharField(blank=True, max_length=100, verbose_name='Service number two')),
                ('service_8', models.CharField(blank=True, max_length=100, verbose_name='Service number three')),
                ('service_9', models.CharField(blank=True, max_length=100, verbose_name='Service number four')),
                ('service_10', models.CharField(blank=True, max_length=100, verbose_name='Service number five')),
                ('buy_now_link', models.URLField(verbose_name='Buy Now Link')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Serial Number')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='realestate/projects')),
                ('field', models.CharField(max_length=255, verbose_name='Title')),
                ('date', models.DateField(verbose_name='Project Done Date')),
                ('number', models.PositiveIntegerField(verbose_name='Serial Number')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=255, verbose_name='Icon')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('dics', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('prop_img', models.ImageField(upload_to='realestate/testimonial', verbose_name='Project Image')),
                ('img', models.ImageField(upload_to='realestate/testimonial', verbose_name='Image')),
                ('prof', models.CharField(max_length=100, verbose_name='Profession')),
                ('disc', models.CharField(max_length=500, verbose_name='Review')),
                ('social_link_f', models.URLField(blank=True, default='facebook.com')),
                ('social_link_t', models.URLField(blank=True, default='twiter.com')),
                ('social_link_i', models.URLField(blank=True, default='instagram.com')),
                ('social_link_l', models.URLField(blank=True, default='linkedin.com')),
            ],
        ),
        migrations.CreateModel(
            name='website_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.CharField(max_length=100, verbose_name='SEO Content')),
                ('keywords', models.CharField(max_length=100, verbose_name='SEO Keyword Comma Seperated')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
