# Generated by Django 3.1.5 on 2021-01-25 15:51

import ckeditor.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='serial Number')),
                ('img_1', models.ImageField(upload_to='realestate/aboutus', verbose_name='About Header Image')),
                ('img_2', models.ImageField(upload_to='realestate/aboutus', verbose_name='Image')),
                ('paragraph', models.CharField(max_length=100, verbose_name='Main Paragrph')),
                ('point_1', models.CharField(max_length=50, verbose_name='Point one')),
                ('point_2', models.CharField(max_length=50, verbose_name='Point two')),
                ('point_3', models.CharField(max_length=50, verbose_name='Point three')),
                ('content', ckeditor.fields.RichTextField(verbose_name='About Us Content Box')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Artitecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Architecture Name')),
                ('img', models.ImageField(upload_to='realestate/architecture', verbose_name='Image')),
                ('social_link_1', models.URLField(blank=True, verbose_name='Twitter link')),
                ('social_link_2', models.URLField(blank=True, verbose_name='Facebook Link')),
                ('social_link_3', models.URLField(blank=True, verbose_name='Instagram link')),
                ('social_link_4', models.URLField(blank=True, verbose_name='Linkedin link')),
                ('number', models.IntegerField(verbose_name='Serical Number')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Messsage')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Serial Number')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Why Contact Us')),
                ('location', models.CharField(max_length=2000, verbose_name='google location')),
                ('address', models.CharField(max_length=20, verbose_name='Address')),
                ('country', models.CharField(default='India', max_length=10, verbose_name='Country')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('tollfree', models.CharField(max_length=13, verbose_name='Toll Free Number')),
                ('social_link_1', models.URLField(blank=True, verbose_name='Twitter link')),
                ('social_link_2', models.URLField(blank=True, verbose_name='Facebook Link')),
                ('social_link_3', models.URLField(blank=True, verbose_name='Instagram link')),
                ('social_link_4', models.URLField(blank=True, verbose_name='Linkedin link')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Question Number')),
                ('question', models.CharField(max_length=50, verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Answer of this question')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Featur Serial Number')),
                ('icon', models.CharField(choices=[('ri-adjust', 'ri-adjust'), ('ri-arrow-down', 'ri-arrow-down'), ('ri-arrow-left', 'ri-arrow-left'), ('ri-arrow-right', 'ri-arrow-right'), ('ri-arrow-up', 'ri-arrow-up'), ('ri-bookmark', 'ri-bookmark'), ('ri-bucket', 'ri-bucket'), ('ri-bullhorn', 'ri-bullhorn'), ('ri-calendar', 'ri-calendar'), ('ri-check-square', 'ri-check-square'), ('ri-check', 'ri-check'), ('ri-chevron-down', 'ri-chevron-down'), ('ri-chevron-down-circle', 'ri-chevron-down-circle'), ('ri-chevron-left-circle', 'ri-chevron-left-circle'), ('ri-chevron-left', 'ri-chevron-left'), ('ri-chevron-right-circle', 'ri-chevron-right-circle'), ('ri-chevron-right-circle', 'ri-chevron-right-circle'), ('ri-chevron-right', 'ri-chevron-right'), ('ri-chevron-top-circle', 'ri-chevron-top-circle'), ('ri-chevron-up', 'ri-chevron-up'), ('ri-clock', 'ri-clock'), ('ri-cloud-download', 'ri-cloud-download'), ('ri-cloud-upload', 'ri-cloud-upload'), ('ri-cloud', 'ri-cloud'), ('ri-comment-bubble', 'ri-comment-bubble'), ('ri-comment-square', 'ri-comment-square'), ('ri-comment-txt-square', 'ri-comment-txt-square'), ('ri-comments-bubble', 'ri-comments-bubble'), ('ri-computer', 'ri-computer'), ('ri-contract', 'ri-contract'), ('ri-crop', 'ri-crop'), ('ri-cross-circle', 'ri-cross-circle'), ('ri-cross', 'ri-cross'), ('ri-cutlery', 'ri-cutlery'), ('ri-diamond', 'ri-diamond'), ('ri-document-add', 'ri-document-add'), ('ri-document-remove', 'ri-document-remove'), ('ri-document', 'ri-document'), ('ri-download', 'ri-download'), ('ri-dribbble', 'ri-dribbble'), ('ri-drop', 'ri-drop'), ('ri-earth', 'ri-earth'), ('ri-envelope', 'ri-envelope'), ('ri-equal-circle', 'ri-equal-circle'), ('ri-exclamation-circle', 'ri-exclamation-circle'), ('ri-exclamation-triangle', 'ri-exclamation-triangle'), ('ri-expand', 'ri-expand'), ('ri-eye-close', 'ri-eye-close'), ('ri-eye', 'ri-eye'), ('ri-facebook', 'ri-facebook'), ('ri-film-play', 'ri-film-play'), ('ri-flag', 'ri-flag'), ('ri-glasses-classic', 'ri-glasses-classic'), ('ri-glasses-hipster', 'ri-glasses-hipster'), ('ri-google-plus', 'ri-google-plus'), ('ri-google', 'ri-google'), ('ri-hamburger-circle', 'ri-hamburger-circle'), ('ri-hamburger', 'ri-hamburger'), ('ri-heart', 'ri-heart'), ('ri-history', 'ri-history'), ('ri-home', 'ri-home'), ('ri-info-circle', 'ri-info-circle'), ('ri-laptop', 'ri-laptop'), ('ri-leaf', 'ri-leaf'), ('ri-link', 'ri-link'), ('ri-list', 'ri-list'), ('ri-location', 'ri-location'), ('ri-lock', 'ri-lock'), ('ri-map-marker', 'ri-map-marker'), ('ri-map', 'ri-map'), ('ri-meh', 'ri-meh'), ('ri-microphone', 'ri-microphone'), ('ri-minus-circle', 'ri-minus-circle'), ('ri-moon', 'ri-moon'), ('ri-move', 'ri-move'), ('ri-music-note-double', 'ri-music-note-double'), ('ri-music-note', 'ri-music-note'), ('ri-mustache', 'ri-mustache'), ('ri-ok-circle', 'ri-ok-circle'), ('ri-paperclip', 'ri-paperclip'), ('ri-pencil-square', 'ri-pencil-square'), ('ri-pencil', 'ri-pencil'), ('ri-plus-circle', 'ri-plus-circle'), ('ri-power-switch', 'ri-power-switch'), ('ri-pushpin', 'ri-pushpin'), ('ri-question-circle', 'ri-question-circle'), ('ri-random', 'ri-random'), ('ri-redo', 'ri-redo'), ('ri-refresh', 'ri-refresh'), ('ri-resize-full', 'ri-resize-full'), ('ri-resize-h', 'ri-resize-h'), ('ri-resize-small', 'ri-resize-small'), ('ri-resize-v', 'ri-resize-v'), ('ri-retweet', 'ri-retweet'), ('ri-rivoli', 'ri-rivoli'), ('ri-sad', 'ri-sad'), ('ri-search-minus', 'ri-search-minus'), ('ri-search-plus', 'ri-search-plus'), ('ri-search', 'ri-search'), ('ri-share-square', 'ri-share-square'), ('ri-share', 'ri-share'), ('ri-shopping-cart', 'ri-shopping-cart'), ('ri-smile', 'ri-smile'), ('ri-star-half-empty', 'ri-star-half-empty'), ('ri-star', 'ri-star'), ('ri-stats', 'ri-stats'), ('ri-sun', 'ri-sun'), ('ri-tag', 'ri-tag'), ('ri-th-large', 'ri-th-large'), ('ri-th-large', 'ri-th-large'), ('ri-th-list', 'ri-th-list'), ('ri-th', 'ri-th'), ('ri-thumbs-down', 'ri-thumbs-down'), ('ri-thumbs-up', 'ri-thumbs-up'), ('ri-trash', 'ri-trash'), ('ri-tumblr', 'ri-tumblr'), ('ri-twitter', 'ri-twitter'), ('ri-undo', 'ri-undo'), ('ri-unlink', 'ri-unlink'), ('ri-unlock', 'ri-unlock'), ('ri-upload', 'ri-upload'), ('ri-user-girl', 'ri-user-girl'), ('ri-user', 'ri-user'), ('ri-users', 'ri-users'), ('ri-volume-level-one', 'ri-volume-level-one'), ('ri-volume-level-three', 'ri-volume-level-three'), ('ri-volume-level-two', 'ri-volume-level-two'), ('ri-volume', 'ri-volume'), ('ri-wrench', 'ri-wrench'), ('ri-youtube-play', 'ri-youtube-play'), ('ri-youtube', 'ri-youtube')], max_length=23)),
                ('title', models.CharField(max_length=100, verbose_name='Feature Name')),
                ('img', models.ImageField(upload_to='realestate/feature', verbose_name='Image of Work')),
                ('paragraph', ckeditor.fields.RichTextField(verbose_name='Feature Discription')),
                ('point_1', models.CharField(blank=True, max_length=50, verbose_name='Point one')),
                ('point_2', models.CharField(blank=True, max_length=50, verbose_name='Point two')),
                ('point_3', models.CharField(blank=True, max_length=50, verbose_name='Point three')),
                ('point_4', models.CharField(blank=True, max_length=50, verbose_name='Point Four')),
                ('point_5', models.CharField(blank=True, max_length=50, verbose_name='Point Five')),
                ('point_6', models.CharField(blank=True, max_length=50, verbose_name='Point Six')),
                ('point_7', models.CharField(blank=True, max_length=50, verbose_name='Point Seven')),
                ('point_8', models.CharField(blank=True, max_length=50, verbose_name='Point Eight')),
                ('point_9', models.CharField(blank=True, max_length=50, verbose_name='Point Nine')),
                ('point_10', models.CharField(blank=True, max_length=50, verbose_name='Point Ten')),
                ('point_11', models.CharField(blank=True, max_length=50, verbose_name='Point Eleven')),
                ('point_12', models.CharField(blank=True, max_length=50, verbose_name='Point Twele')),
                ('point_13', models.CharField(blank=True, max_length=50, verbose_name='Point Thirteen')),
                ('point_14', models.CharField(blank=True, max_length=50, verbose_name='Point Fourteen')),
                ('point_15', models.CharField(blank=True, max_length=50, verbose_name='Point Fifteen')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Company Name')),
                ('paragraph', models.CharField(max_length=50, verbose_name='Content Box')),
                ('link_1', models.URLField(verbose_name='Twitter link')),
                ('link_2', models.URLField(verbose_name='Facebook link')),
                ('link_3', models.URLField(verbose_name='Instagram link')),
                ('link_4', models.URLField(verbose_name='Linkedin link')),
                ('serial_number', models.IntegerField(verbose_name='Serial Number')),
            ],
            options={
                'ordering': ['-serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_img', models.ImageField(upload_to='realestate/header', verbose_name='Header Image')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('content', models.CharField(max_length=200, verbose_name='Content Box')),
                ('number', models.IntegerField(verbose_name='Serial Number')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name=' Serial Number')),
                ('title', models.CharField(max_length=10, verbose_name='Package Name')),
                ('service_1', models.CharField(blank=True, max_length=20, verbose_name='Service')),
                ('service_2', models.CharField(blank=True, max_length=20, verbose_name='Service number two')),
                ('service_3', models.CharField(blank=True, max_length=20, verbose_name='Service number three')),
                ('service_4', models.CharField(blank=True, max_length=20, verbose_name='Service number four')),
                ('service_5', models.CharField(blank=True, max_length=20, verbose_name='Service number five')),
                ('buy_now_link', models.URLField(verbose_name='Buy Now Link')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='PrivancyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Serial Number')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='realestate/projects')),
                ('field', models.CharField(max_length=255, verbose_name='Title')),
                ('date', models.DateField(verbose_name='Project Done Date')),
                ('number', models.IntegerField(verbose_name='Serial Number')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=255, verbose_name='Synbol')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('dics', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('number', models.IntegerField(verbose_name='Number')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('prop_img', models.ImageField(upload_to='realestate/testimonial', verbose_name='Project Image')),
                ('img', models.ImageField(upload_to='realestate/testimonial', verbose_name='Image')),
                ('prof', models.CharField(max_length=100, verbose_name='Profession')),
                ('disc', models.CharField(max_length=500, verbose_name='Review')),
                ('social_link_f', models.URLField(blank=True, default='facebook.com')),
                ('social_link_t', models.URLField(blank=True, default='twiter.com')),
                ('social_link_i', models.URLField(blank=True, default='instagram.com')),
                ('social_link_l', models.URLField(blank=True, default='linkedin.com')),
            ],
        ),
        migrations.CreateModel(
            name='website_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.CharField(max_length=100, verbose_name='SEO Content')),
                ('keywords', models.CharField(max_length=100, verbose_name='SEO Keyword Comma Seperated')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
