# Generated by Django 3.1.5 on 2021-01-26 07:36

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='about_this',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='About This Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='additional_img_1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='realestate/property', verbose_name='Side image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='additional_img_2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='realestate/property', verbose_name='Side image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='property_video',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000, verbose_name='Iframe of your property video'),
            preserve_default=False,
        ),
    ]
