# Generated by Django 3.1.5 on 2021-01-28 09:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=500, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='header',
            name='additional_img_1',
            field=models.ImageField(blank=True, upload_to='realestate/property', verbose_name='Side image'),
        ),
        migrations.AlterField(
            model_name='header',
            name='additional_img_2',
            field=models.ImageField(blank=True, upload_to='realestate/property', verbose_name='Side image'),
        ),
        migrations.AlterField(
            model_name='header',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='header',
            name='loacation',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Google location of Property'),
        ),
        migrations.AlterField(
            model_name='header',
            name='property_video',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Iframe of your property video'),
        ),
        migrations.AlterField(
            model_name='price',
            name='buy_now_link',
            field=models.URLField(blank=True, verbose_name='Buy Now Link'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='prof',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profession'),
        ),
    ]
