# Generated by Django 3.1.5 on 2021-01-24 12:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Serial Number')),
                ('location', models.CharField(max_length=30, verbose_name='Location')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('tollfree', models.CharField(max_length=13, verbose_name='Toll Free Number')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
