# Generated by Django 3.1.5 on 2021-01-25 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_title',
            name='content',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='SEO Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_title',
            name='keywords',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='SEO Keyword Comma Seperated'),
            preserve_default=False,
        ),
    ]
