# Generated by Django 3.1.5 on 2021-01-26 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210126_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='contact_person',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='realestate/contact_person', verbose_name='Dealer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='loacation',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000, verbose_name='Google location of Property'),
            preserve_default=False,
        ),
    ]
