# Generated by Django 3.1.5 on 2021-01-28 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210127_1949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivancyPolicy',
            new_name='PrivacyPolicy',
        ),
    ]
