# Generated by Django 3.1.5 on 2021-01-29 05:33

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210128_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='content',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='header',
            name='status',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], max_length=10, verbose_name='Perpose'),
        ),
    ]
