# Generated by Django 3.1.5 on 2021-01-25 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210125_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='img_1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='realestate/aboutus', verbose_name='About Header Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='img_2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='realestate/aboutus', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
