# Generated by Django 3.1.5 on 2021-01-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210126_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='header',
            name='contact_person',
            field=models.ManyToManyField(to='main.Artitecture'),
        ),
    ]
