# Generated by Django 3.1.5 on 2021-01-25 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210125_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Project Done Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='field',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
