# Generated by Django 3.1.5 on 2021-01-29 11:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210129_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Featur Serial Number')),
                ('icon', models.CharField(max_length=23, verbose_name='Icon')),
                ('title', models.CharField(max_length=100, verbose_name='Feature Name')),
                ('img', models.ImageField(upload_to='realestate/feature', verbose_name='Image of Work')),
                ('paragraph', ckeditor.fields.RichTextField(verbose_name='Feature Discription')),
                ('point_1', models.CharField(blank=True, max_length=50, verbose_name='Requrements')),
                ('point_2', models.CharField(blank=True, max_length=50, verbose_name='Requrements')),
                ('point_3', models.CharField(blank=True, max_length=50, verbose_name='Requrements')),
                ('point_4', models.CharField(blank=True, max_length=50, verbose_name='Requrements')),
                ('point_5', models.CharField(blank=True, max_length=50, verbose_name='Requrements')),
                ('point_6', models.CharField(blank=True, max_length=50, verbose_name='Requrements')),
                ('point_7', models.CharField(blank=True, max_length=50, verbose_name='Requrements')),
                ('point_8', models.CharField(blank=True, max_length=50, verbose_name='Requrements')),
                ('point_9', models.CharField(blank=True, max_length=50, verbose_name='Requrements')),
                ('point_10', models.CharField(blank=True, max_length=50, verbose_name='Requrements')),
                ('point_11', models.CharField(blank=True, max_length=50, verbose_name='Requrements')),
                ('point_12', models.CharField(blank=True, max_length=50, verbose_name='Requrements')),
                ('point_13', models.CharField(blank=True, max_length=50, verbose_name='Requrements')),
                ('point_14', models.CharField(blank=True, max_length=50, verbose_name='Requrements')),
                ('point_15', models.CharField(blank=True, max_length=50, verbose_name='Requrements')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
