# Generated by Django 3.1.5 on 2021-01-26 07:58

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210126_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='artitecture',
            name='about_me',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='About Me'),
            preserve_default=False,
        ),
    ]
