# Generated by Django 3.1.5 on 2021-01-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_artitecture_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='contact_person',
        ),
    ]
