# Generated by Django 3.1.5 on 2021-01-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='point_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='career',
            name='point_10',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requrements'),
        ),
        migrations.AlterField(
            model_name='career',
            name='point_11',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requrements'),
        ),
        migrations.AlterField(
            model_name='career',
            name='point_12',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requrements'),
        ),
        migrations.AlterField(
            model_name='career',
            name='point_13',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requrements'),
        ),
        migrations.AlterField(
            model_name='career',
            name='point_14',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requrements'),
        ),
        migrations.AlterField(
            model_name='career',
            name='point_15',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requrements'),
        ),
        migrations.AlterField(
            model_name='career',
            name='point_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requrements'),
        ),
        migrations.AlterField(
            model_name='career',
            name='point_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requrements'),
        ),
        migrations.AlterField(
            model_name='career',
            name='point_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requrements'),
        ),
        migrations.AlterField(
            model_name='career',
            name='point_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requrements'),
        ),
        migrations.AlterField(
            model_name='career',
            name='point_6',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requrements'),
        ),
        migrations.AlterField(
            model_name='career',
            name='point_7',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requrements'),
        ),
        migrations.AlterField(
            model_name='career',
            name='point_8',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requrements'),
        ),
        migrations.AlterField(
            model_name='career',
            name='point_9',
            field=models.CharField(blank=True, max_length=200, verbose_name='Requrements'),
        ),
    ]
