# Generated by Django 3.1.5 on 2021-01-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_header_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='number',
            field=models.PositiveIntegerField(verbose_name='serial Number'),
        ),
        migrations.AlterField(
            model_name='artitecture',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Serical Number'),
        ),
        migrations.AlterField(
            model_name='contact_detail',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Question Number'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(max_length=23, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Featur Serial Number'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='serial_number',
            field=models.PositiveIntegerField(verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='header',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='price',
            name='number',
            field=models.PositiveIntegerField(verbose_name=' Serial Number'),
        ),
        migrations.AlterField(
            model_name='privancypolicy',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='services',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='services',
            name='symbol',
            field=models.CharField(blank=True, max_length=255, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='website_title',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Number'),
        ),
    ]
