# Generated by Django 3.1.5 on 2021-01-25 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210125_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='artitecture',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='realestate/architecture', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
