# Generated by Django 3.1.5 on 2021-01-29 12:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_career_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='url',
            field=models.URLField(blank=True, verbose_name='application url'),
        ),
        migrations.AlterField(
            model_name='career',
            name='paragraph',
            field=ckeditor.fields.RichTextField(verbose_name='Post Discription'),
        ),
        migrations.AlterField(
            model_name='career',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Post Name'),
        ),
    ]
