# Generated by Django 3.1.5 on 2021-01-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_artitecture_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='artitecture',
            name='social_link_2',
            field=models.URLField(blank=True, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='artitecture',
            name='social_link_3',
            field=models.URLField(blank=True, verbose_name='Instagram link'),
        ),
        migrations.AddField(
            model_name='artitecture',
            name='social_link_4',
            field=models.URLField(blank=True, verbose_name='Linkedin link'),
        ),
        migrations.AlterField(
            model_name='artitecture',
            name='social_link_1',
            field=models.URLField(blank=True, verbose_name='Twitter link'),
        ),
    ]
