# Generated by Django 3.1.5 on 2021-01-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210129_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='area',
            field=models.PositiveIntegerField(blank=True, verbose_name='Area In Squre Ft.'),
        ),
        migrations.AlterField(
            model_name='header',
            name='bath',
            field=models.PositiveIntegerField(blank=True, verbose_name='Nomber of Baths'),
        ),
        migrations.AlterField(
            model_name='header',
            name='beds',
            field=models.PositiveIntegerField(blank=True, verbose_name='Number of Bedroom'),
        ),
        migrations.AlterField(
            model_name='header',
            name='content',
            field=models.CharField(blank=True, max_length=200, verbose_name='Content Box'),
        ),
        migrations.AlterField(
            model_name='header',
            name='hall',
            field=models.PositiveIntegerField(blank=True, verbose_name='Number of Hall'),
        ),
        migrations.AlterField(
            model_name='header',
            name='price',
            field=models.PositiveIntegerField(blank=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='header',
            name='status',
            field=models.CharField(blank=True, choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('For Design', 'For Design')], max_length=10, verbose_name='Perpose'),
        ),
    ]
