# Generated by Django 3.1.5 on 2021-01-25 14:35

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210125_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_detail',
            name='content',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='Why Contact Us'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_detail',
            name='social_link_1',
            field=models.URLField(blank=True, verbose_name='Twitter link'),
        ),
        migrations.AddField(
            model_name='contact_detail',
            name='social_link_2',
            field=models.URLField(blank=True, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='contact_detail',
            name='social_link_3',
            field=models.URLField(blank=True, verbose_name='Instagram link'),
        ),
        migrations.AddField(
            model_name='contact_detail',
            name='social_link_4',
            field=models.URLField(blank=True, verbose_name='Linkedin link'),
        ),
    ]
