# Generated by Django 3.1.5 on 2021-01-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210125_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_detail',
            name='location',
            field=models.URLField(verbose_name='Google Location Link'),
        ),
    ]
