# Generated by Django 3.1.5 on 2021-02-13 08:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210130_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('blog_image', models.ImageField(upload_to='blog_photos/', verbose_name='Post Image')),
                ('disc', ckeditor.fields.RichTextField()),
                ('catagory', models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential'), ('Clinic', 'Hospital'), ('Institutional', 'Institutional'), ('Interior', 'Interior'), ('Architecture', 'Architecture')], max_length=200, verbose_name='Category')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Current_Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.IntegerField(verbose_name='Serial Number')),
                ('project_title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('clint_name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('loc', models.CharField(blank=True, max_length=500, verbose_name='Address of this Project')),
                ('main_image', models.ImageField(upload_to='projects/proposed_projects', verbose_name='main Image')),
                ('second_image', models.ImageField(upload_to='projects/proposed_projects', verbose_name='Second Image')),
                ('third_image', models.ImageField(upload_to='projects/proposed_projects', verbose_name='Third Image')),
                ('fouth_image', models.ImageField(upload_to='projects/proposed_projects', verbose_name='Fourth Image')),
                ('disc', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'ordering': ['project_number'],
            },
        ),
        migrations.CreateModel(
            name='Past_Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.IntegerField(verbose_name='Serial Number')),
                ('project_title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('clint_name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('loc', models.CharField(blank=True, max_length=500, verbose_name='Address of this Project')),
                ('main_image', models.ImageField(upload_to='projects/proposed_projects', verbose_name='main Image')),
                ('second_image', models.ImageField(upload_to='projects/proposed_projects', verbose_name='Second Image')),
                ('third_image', models.ImageField(upload_to='projects/proposed_projects', verbose_name='Third Image')),
                ('fouth_image', models.ImageField(upload_to='projects/proposed_projects', verbose_name='Fourth Image')),
                ('disc', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'ordering': ['project_number'],
            },
        ),
        migrations.CreateModel(
            name='Proposed_Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.IntegerField(verbose_name='Serial Number')),
                ('project_title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('clint_name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('loc', models.CharField(blank=True, max_length=500, verbose_name='Address of this Project')),
                ('main_image', models.ImageField(upload_to='projects/proposed_projects', verbose_name='main Image')),
                ('second_image', models.ImageField(upload_to='projects/proposed_projects', verbose_name='Second Image')),
                ('third_image', models.ImageField(upload_to='projects/proposed_projects', verbose_name='Third Image')),
                ('fouth_image', models.ImageField(upload_to='projects/proposed_projects', verbose_name='Fourth Image')),
                ('disc', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'ordering': ['project_number'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('loacation', models.CharField(max_length=300, verbose_name='location')),
                ('disc', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blog')),
            ],
        ),
    ]
