# Generated by Django 3.1.5 on 2021-01-25 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210125_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_detail',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
