# Generated by Django 3.1.5 on 2021-02-13 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_blog_comment_current_projects_past_projects_proposed_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_projects',
            name='filter_by',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential'), ('Clinic', 'Hospital'), ('Institutional', 'Institutional'), ('Interior', 'Interior'), ('Architecture', 'Architecture')], default=django.utils.timezone.now, max_length=100, verbose_name='filter By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='past_projects',
            name='filter_by',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential'), ('Clinic', 'Hospital'), ('Institutional', 'Institutional'), ('Interior', 'Interior'), ('Architecture', 'Architecture')], default=django.utils.timezone.now, max_length=100, verbose_name='filter By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposed_projects',
            name='filter_by',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential'), ('Clinic', 'Hospital'), ('Institutional', 'Institutional'), ('Interior', 'Interior'), ('Architecture', 'Architecture')], default=django.utils.timezone.now, max_length=100, verbose_name='filter By'),
            preserve_default=False,
        ),
    ]
