# Generated by Django 3.1.5 on 2021-02-13 09:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210213_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Projects_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField(verbose_name='Serial Number')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'ordering': ['-serial_no'],
            },
        ),
        migrations.CreateModel(
            name='Past_Projects_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField(verbose_name='Serial Number')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'ordering': ['-serial_no'],
            },
        ),
        migrations.CreateModel(
            name='Proposed_Projects_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField(verbose_name='Serial Number')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'ordering': ['-serial_no'],
            },
        ),
        migrations.AlterField(
            model_name='current_projects',
            name='project_number',
            field=models.PositiveIntegerField(verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='past_projects',
            name='project_number',
            field=models.PositiveIntegerField(verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='proposed_projects',
            name='project_number',
            field=models.PositiveIntegerField(verbose_name='Serial Number'),
        ),
    ]
