# Generated by Django 3.1.5 on 2021-01-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contact_detail_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_detail',
            name='country',
            field=models.CharField(default='India', max_length=10, verbose_name='Country'),
        ),
    ]
