# Generated by Django 3.1.5 on 2021-01-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contact_detail_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_detail',
            name='location',
            field=models.CharField(max_length=2000, verbose_name='Google Location Link'),
        ),
    ]
