# Generated by Django 3.1.5 on 2021-02-14 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210213_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='overview',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='overview'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='catagory',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential'), ('Clinic/Hospital', 'Clinic/Hospital'), ('Institutional', 'Institutional'), ('Interior', 'Interior'), ('Architecture', 'Architecture')], max_length=200, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='current_projects',
            name='filter_by',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential'), ('Clinic/Hospital', 'Clinic/Hospital'), ('Institutional', 'Institutional'), ('Interior', 'Interior'), ('Architecture', 'Architecture')], max_length=100, verbose_name='filter By'),
        ),
        migrations.AlterField(
            model_name='past_projects',
            name='filter_by',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential'), ('Clinic/Hospital', 'Clinic/Hospital'), ('Institutional', 'Institutional'), ('Interior', 'Interior'), ('Architecture', 'Architecture')], max_length=100, verbose_name='filter By'),
        ),
        migrations.AlterField(
            model_name='proposed_projects',
            name='filter_by',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential'), ('Clinic/Hospital', 'Clinic/Hospital'), ('Institutional', 'Institutional'), ('Interior', 'Interior'), ('Architecture', 'Architecture')], max_length=100, verbose_name='filter By'),
        ),
    ]
