# Generated by Django 3.1.5 on 2021-02-14 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210214_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='loacation',
            field=models.CharField(blank=True, max_length=300, verbose_name='location'),
        ),
    ]
