# Generated by Django 3.1.5 on 2021-01-25 15:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210125_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_detail',
            name='location',
            field=ckeditor.fields.RichTextField(verbose_name='google location'),
        ),
    ]
