# Generated by Django 3.1.5 on 2021-01-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210125_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_detail',
            name='location',
            field=models.CharField(max_length=2000, verbose_name='google location'),
        ),
    ]
